#!/bin/bash
#: Title	: Backup service file
#: Date 	: Nov 20 2022
#: Author 	: Jacob Lloyd and Coburn Nguyen
#: Version 	: 1.0
#: Desc 	: Service file to run back up script
#: Options 	: None

[Unit]
Description=backup files from a server to a backup server using rsync

[Service]
Type=oneshot
ExecStart=/opt/.git/2420_week11_Lab/backup-script

[Install]
WantedBy=multi-user.target
