#!/bin/bash
#: Title       : Backup file to server
#: Date        : Nov 20 2022
#: Author      : Coburn Nguyen & Jacob Lloyd
#: Version     : 1.0
#: Description : Backup files from server to backup server using rsync
#: Options     : None

. /home/SO-user/.git/2420_week11_Lab/config.sh

rsync -r ${FILE_PATH_COPY} backup-user@${IP_DESTINATION}:/home/backup-user/BackUp -e "ssh -i ~/.ssh/backup-server-KEY"
